import {
  ChurchProfile,
  FounderFamilyData,
  PastorScheduleItem,
  NoticeItem,
  ChurchEvent,
  BookingRecord,
  GroupItem,
  GroupMessage,
  PaymentSettings,
  PrayerRequest,
  ChildProfile,
  QuizQuestion,
  BibleStory,
  MemoryVerseAssignment,
  SundaySchoolClass,
  BadgeItem,
  LeaderboardChild,
  UserProfile,
} from '../types';

export const INITIAL_CURRENT_USER: UserProfile = {
  id: 'usr_admin_1',
  name: 'Pastor Daniel Nagashetty',
  email: 'pastor.daniel@aajmchurch.org',
  phone: '+91 98490 12345',
  role: 'Super Admin',
  avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
  childrenIds: ['child_1', 'child_2'],
  parentPin: '1234',
};

export interface ChurchAccountItem extends UserProfile {
  passwordHash?: string;
  department?: string;
}

export const INITIAL_CHURCH_ACCOUNTS: ChurchAccountItem[] = [
  {
    id: 'usr_admin_1',
    name: 'Pastor Daniel Nagashetty',
    email: 'pastor.daniel@aajmchurch.org',
    phone: '+91 98490 12345',
    role: 'Super Admin',
    department: 'Senior Leadership & Pastoral Care',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=256&q=80',
    childrenIds: ['child_1', 'child_2'],
    parentPin: '1234',
    passwordHash: 'password123',
  },
  {
    id: 'usr_benny',
    name: 'Benny Nagashetty',
    email: 'bennynagishetti@gmail.com',
    phone: '+91 98490 54321',
    role: 'Group Leader',
    department: 'Youth & Fellowship Ministry',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=256&q=80',
    assignedGroupIds: ['grp_youth', 'grp_worship'],
    parentPin: '1234',
    passwordHash: 'password123',
  },
  {
    id: 'usr_teacher_1',
    name: 'Teacher Rachel',
    email: 'teacher.rachel@aajmchurch.org',
    phone: '+91 98490 67890',
    role: 'Sunday School Teacher',
    department: 'Children & Sunday School Education',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=256&q=80',
    assignedClassIds: ['cls_kingdom_kids'],
    parentPin: '1234',
    passwordHash: 'password123',
  },
  {
    id: 'usr_host_1',
    name: 'Deacon John (Host)',
    email: 'deacon.john@aajmchurch.org',
    phone: '+91 98490 33445',
    role: 'Host',
    department: 'Event & Facility Hosting',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=256&q=80',
    parentPin: '1234',
    passwordHash: 'password123',
  },
  {
    id: 'usr_parent_1',
    name: 'Brother Samuel & Family',
    email: 'brother.samuel@aajmchurch.org',
    phone: '+91 98490 99887',
    role: 'Parent',
    department: 'Family Ministry & Prayer Cell',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=256&q=80',
    childrenIds: ['child_1'],
    parentPin: '1234',
    passwordHash: 'password123',
  },
  {
    id: 'usr_member_1',
    name: 'Sister Priya Grace',
    email: 'priya.grace@aajmchurch.org',
    phone: '+91 98490 11223',
    role: 'Member',
    department: 'Choir & Intercessory Prayer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=256&q=80',
    passwordHash: 'password123',
  },
  {
    id: 'usr_child_1',
    name: 'Joshua Nagashetty (Kids)',
    email: 'joshua@aajmchurch.org',
    phone: '+91 98490 12345',
    role: 'Child',
    department: 'Sunday School - Kingdom Kids',
    avatar: '👦',
    passwordHash: 'password123',
  },
];

export const INITIAL_CHURCH_PROFILE: ChurchProfile = {
  name: 'AAJM CHURCH',
  tagline: 'All Are Joyful Ministries',
  logoUrl: '',
  pastorName: 'Pastor Daniel Nagashetty',
  founderName: 'Pastor Daniel Nagashetty',
  about:
    'AAJM (All Are Joyful Ministries) Church is a Christ-centered, vibrant spiritual family dedicated to glorifying God, spreading the Gospel of Jesus Christ, nurturing believers of all generations, and serving the needy with deep compassion.',
  history:
    'Founded under the divine calling and vision given to Pastor Daniel Nagashetty, AAJM Church began as a humble prayer gathering and has grown into a beacon of hope, salvation, healing, and community empowerment touching thousands of families across Telangana and worldwide.',
  mission:
    'To preach the uncompromised Word of God, transform lives through the power of the Holy Spirit, equip disciples, and raise a joyful, faith-filled generation.',
  vision:
    'To see every family blessed, every child rooted in Christ, and every community transformed through love, prayer, and selfless service.',
  contactPhone: '+91 98490 12345 / +91 40 2780 1234',
  contactEmail: 'contact@aajmchurch.org',
  address: 'Plot No. 42, Joyful Nagar, Main Church Road, Near Metro Station, Secunderabad, Hyderabad, Telangana 500003',
  city: 'Secunderabad / Hyderabad',
  state: 'Telangana',
  pinCode: '500003',
  mapCoordinates: { lat: 17.4399, lng: 78.4983 },
  socialLinks: {
    youtube: 'https://youtube.com/@aajmchurch',
    facebook: 'https://facebook.com/aajmchurch',
    instagram: 'https://instagram.com/aajmchurch',
    whatsapp: 'https://wa.me/919849012345',
  },
  serviceTimings: [
    { day: 'Sunday', time: '07:30 AM - 09:30 AM', serviceName: '1st Morning Worship & Holy Communion (Telugu)' },
    { day: 'Sunday', time: '10:00 AM - 12:30 PM', serviceName: '2nd Celebration Worship Service (English & Telugu)' },
    { day: 'Sunday', time: '10:00 AM - 12:00 PM', serviceName: 'Children Sunday School & Youth Service' },
    { day: 'Wednesday', time: '06:30 PM - 08:00 PM', serviceName: 'Mid-Week Word Study & Healing Prayers' },
    { day: 'Friday', time: '10:30 AM - 01:30 PM', serviceName: 'Fasting & Deliverance Prayer Service' },
    { day: 'Saturday', time: '06:30 PM - 08:00 PM', serviceName: 'Youth Fellowship & Choir Rehearsal' },
  ],
};

export const INITIAL_FOUNDER_FAMILY: FounderFamilyData = {
  pastorBio:
    'Pastor Daniel Nagashetty is the Founder and Senior Pastor of AAJM Church. Called into full-time ministry with a burning passion for revival, pastoral care, and scriptural truth, Pastor Daniel has ministered with unwavering faith for over two decades. His visionary leadership and warm fatherly heart continue to guide the congregation in joy and righteousness.',
  familyBio:
    'Pastor Daniel Nagashetty is blessed in life and ministry with his beloved wife Dorka Rani, his daughter Blessy, and his son Benny. The entire family is devotedly engaged in church ministry, worship, Sunday School, and humanitarian outreach.',
  churchHistory:
    'AAJM Church started with dedicated prayer warriors seeking revival. Today, the church hosts multiple weekly services, extensive charity programs for the underprivileged, a vibrant children ministry, and regular regional gospel outreach.',
  ministryHistory:
    'From village gospel crusades and television broadcasts to comprehensive community welfare, AAJM Church has established free medical camps, food distribution drives, and youth leadership mentorship.',
  familyTimeline: [
    { year: '2004', title: 'Ministry Commissioning', description: 'Pastor Daniel Nagashetty dedicated his life to full-time gospel service and prayer ministry.' },
    { year: '2009', title: 'AAJM Ministry Inception', description: 'All Are Joyful Ministries was founded in Secunderabad, welcoming all seekers of truth.' },
    { year: '2015', title: 'Sanctuary Dedication', description: 'The main church sanctuary was built and dedicated to God for worship and community services.' },
    { year: '2020', title: 'Digital & Media Outreach', description: 'Launched online broadcasts, mobile fellowship groups, and expanded youth missions.' },
    { year: '2026', title: 'Generational Growth & VBS', description: 'Expanding Sunday School classrooms, digital community engagement, and relief missions.' },
  ],
  members: [
    {
      id: 'fam_1',
      name: 'Pastor Daniel Nagashetty',
      relation: 'Founder/Pastor',
      title: 'Founder & Senior Pastor',
      bio: 'Visionary leader, teacher of God’s Word, and shepherd of AAJM Church.',
      photoUrl: '', // user can upload or will display portrait
      displayOrder: 1,
    },
    {
      id: 'fam_2',
      name: 'Dorka Rani',
      relation: 'Wife',
      title: 'Pastor’s Wife & Women’s Ministry Leader',
      bio: 'Leader of AAJM Women’s Fellowship, intercessor, and pillar of care for church families.',
      photoUrl: '',
      displayOrder: 2,
    },
    {
      id: 'fam_3',
      name: 'Blessy',
      relation: 'Daughter',
      title: 'Daughter',
      bio: 'Actively serves in worship ministry, children education, and multimedia outreach.',
      photoUrl: '',
      displayOrder: 3,
    },
    {
      id: 'fam_4',
      name: 'Benny',
      relation: 'Son',
      title: 'Son',
      bio: 'Involved in youth leadership, audio-visual technical team, and outreach activities.',
      photoUrl: '',
      displayOrder: 4,
    },
  ],
};

export const INITIAL_PASTOR_SCHEDULE: PastorScheduleItem[] = [
  {
    id: 'sched_mon',
    day: 'Monday',
    time: '09:00 AM - 01:00 PM',
    title: 'Pastoral Office & Spiritual Counseling',
    location: 'Pastor Daniel’s Study, Main Sanctuary',
    description: 'One-on-one appointments, prayer guidance, and spiritual counseling for church members.',
    enabled: true,
    order: 1,
  },
  {
    id: 'sched_tue',
    day: 'Tuesday',
    time: '06:00 PM - 08:30 PM',
    title: 'Cottage Prayer & Family Visitation',
    location: 'Church Member Homes (Zonal Rotation)',
    description: 'Pastoral home visits, house blessings, and intimate zonal fellowship prayers.',
    enabled: true,
    order: 2,
  },
  {
    id: 'sched_wed',
    day: 'Wednesday',
    time: '06:30 PM - 08:00 PM',
    title: 'Mid-Week Bible Study & Healing Prayer',
    location: 'Main Church Auditorium',
    description: 'Expository verse-by-verse scripture teaching led by Pastor Daniel Nagashetty.',
    enabled: true,
    order: 3,
  },
  {
    id: 'sched_thu',
    day: 'Thursday',
    time: '10:00 AM - 02:00 PM',
    title: 'Intercessory Prayer & Outreach Planning',
    location: 'Upper Room Prayer Hall',
    description: 'Special prayer for church families, city peace, hospital patients, and global missions.',
    enabled: true,
    order: 4,
  },
  {
    id: 'sched_fri',
    day: 'Friday',
    time: '10:30 AM - 01:30 PM',
    title: 'Fasting Prayer & Deliverance Service',
    location: 'Main Sanctuary',
    description: 'Congregational fasting prayer, individual anointing, and breakthroughs.',
    enabled: true,
    order: 5,
  },
  {
    id: 'sched_sat',
    day: 'Saturday',
    time: '06:00 PM - 08:30 PM',
    title: 'Youth Mentorship & Worship Preparation',
    location: 'Youth Center & Choir Stage',
    description: 'Mentoring young believers, leadership coaching, and Sunday service preparations.',
    enabled: true,
    order: 6,
  },
  {
    id: 'sched_sun',
    day: 'Sunday',
    time: '07:30 AM & 10:00 AM',
    title: 'Sunday Worship Services & Holy Communion',
    location: 'Main Sanctuary',
    description: 'Divine Word proclamation, Holy Communion, dedicating babies, and congregational worship.',
    enabled: true,
    order: 7,
  },
];

export const INITIAL_NOTICES: NoticeItem[] = [
  {
    id: 'notice_1',
    title: 'Annual Harvest & Thanksgiving Celebration',
    description:
      'We joyfully invite all church families to our Annual Thanksgiving Sunday Service. Special guest speakers, choir performances, and fellowship lunch following the second service.',
    author: 'Pastor Daniel Nagashetty',
    date: '2026-09-27',
    time: '10:00 AM',
    category: 'Events',
    priority: 'Important',
    audience: 'Everyone',
    publishDate: '2026-09-18',
    status: 'Published',
    viewsCount: 420,
  },
  {
    id: 'notice_2',
    title: 'Urgent Intercessory Prayer for Sister Grace’s Family',
    description:
      'Please uphold our dear church member Sister Grace and family in prayers as her mother is undergoing surgery this Thursday. Let us stand united in faith.',
    author: 'Intercessory Prayer Team',
    date: '2026-09-20',
    time: '06:00 AM',
    category: 'Prayer',
    priority: 'Emergency',
    audience: 'Everyone',
    publishDate: '2026-09-19',
    status: 'Published',
    viewsCount: 312,
  },
  {
    id: 'notice_3',
    title: 'Children Bible Quiz & Sunday School Stars Award Ceremony',
    description:
      'All parents are requested to encourage their children to submit their Weekly Memory Verses before Saturday. Bible Stars and special trophy badges will be awarded this Sunday.',
    author: 'Sunday School Department',
    date: '2026-09-27',
    time: '11:30 AM',
    category: 'Church',
    priority: 'Normal',
    audience: 'Everyone',
    publishDate: '2026-09-17',
    status: 'Published',
    viewsCount: 285,
  },
  {
    id: 'notice_4',
    title: 'Youth Night & Live Acoustic Worship Fellowship',
    description:
      'All young people aged 13-30 are invited for an evening of dynamic worship, group discussions, and life-skill testimony sessions.',
    author: 'AAJM Youth Fellowship',
    date: '2026-10-03',
    time: '06:00 PM',
    category: 'Groups',
    priority: 'Normal',
    audience: 'Specific Group',
    targetGroupId: 'grp_youth',
    publishDate: '2026-09-15',
    status: 'Published',
    viewsCount: 198,
  },
];

export const INITIAL_EVENTS: ChurchEvent[] = [
  {
    id: 'evt_1',
    title: 'Sunday Celebration Service & Communion',
    description: 'Worship with the AAJM choir followed by inspiring message from Pastor Daniel Nagashetty and Holy Communion.',
    date: '2026-09-27',
    startTime: '10:00 AM',
    endTime: '12:30 PM',
    location: 'AAJM Main Sanctuary, Joyful Nagar',
    organizer: 'AAJM Pastoral Team',
    capacity: 600,
    rsvpCount: 245,
    isRsvpd: true,
    category: 'Sunday Service',
  },
  {
    id: 'evt_2',
    title: 'Friday Deliverance & Fasting Prayer',
    description: 'A powerful atmosphere of worship, scripture declaration, and personal anointing prayer.',
    date: '2026-09-25',
    startTime: '10:30 AM',
    endTime: '01:30 PM',
    location: 'Upper Prayer Hall',
    organizer: 'Pastor Daniel Nagashetty',
    capacity: 250,
    rsvpCount: 110,
    isRsvpd: false,
    category: 'Fasting Prayer',
  },
  {
    id: 'evt_3',
    title: 'Annual Youth Conference 2026',
    description: 'Empowering the next generation for kingdom leadership, music ministry, and career excellence.',
    date: '2026-10-10',
    startTime: '09:30 AM',
    endTime: '04:30 PM',
    location: 'Church Convention Hall',
    organizer: 'Benny Nagashetty & Youth Leaders',
    capacity: 350,
    rsvpCount: 192,
    isRsvpd: true,
    meetingLink: 'https://meet.livekit.io/aajm-youth-conf',
    category: 'Youth Meeting',
  },
  {
    id: 'evt_4',
    title: 'Women’s Fellowship & Charity Food Drive',
    description: 'Monthly gathering of mothers and sisters in Christ, organizing ration hampers for widows and orphans.',
    date: '2026-10-02',
    startTime: '04:00 PM',
    endTime: '06:00 PM',
    location: 'Fellowship Hall',
    organizer: 'Sister Dorka Rani',
    capacity: 150,
    rsvpCount: 88,
    isRsvpd: false,
    category: 'Fellowship',
  },
];

export const INITIAL_BOOKINGS: BookingRecord[] = [
  {
    id: 'bk_1',
    name: 'Brother Samuel Rao',
    phoneNumber: '+91 94401 23456',
    location: 'Pastor Office, Sanctuary',
    bookingDate: '2026-09-21',
    purpose: 'Child Dedication Prayer & Counseling',
    startTime: '10:00',
    endTime: '11:00',
    status: 'CONFIRMED',
    createdAt: '2026-09-18T10:00:00Z',
    memberId: 'usr_samuel',
    remindersSent: ['3_days', '2_days'],
  },
  {
    id: 'bk_2',
    name: 'Sister Mary Varghese',
    phoneNumber: '+91 98850 78901',
    location: 'Main Sanctuary',
    bookingDate: '2026-09-22',
    purpose: 'New House Blessing Thanksgiving Prayer',
    startTime: '16:00',
    endTime: '17:30',
    status: 'PENDING',
    createdAt: '2026-09-19T08:00:00Z',
    memberId: 'usr_mary',
    remindersSent: [],
  },
  {
    id: 'bk_3',
    name: 'Brother David Kumar',
    phoneNumber: '+91 97001 54321',
    location: 'Pastor Study',
    bookingDate: '2026-09-23',
    purpose: 'Pre-Marital Spiritual Counseling',
    startTime: '11:00',
    endTime: '12:00',
    status: 'CONFIRMED',
    createdAt: '2026-09-17T14:30:00Z',
    memberId: 'usr_david',
    remindersSent: ['3_days'],
  },
  {
    id: 'bk_4',
    name: 'Brother Paul Raj',
    phoneNumber: '+91 99123 45678',
    location: 'Fellowship Hall',
    bookingDate: '2026-09-24',
    purpose: 'Commercial Photography Studio (Unrelated)',
    startTime: '14:00',
    endTime: '17:00',
    status: 'REJECTED',
    createdAt: '2026-09-16T12:00:00Z',
    rejectionReason: 'Sanctuary premises reserved strictly for Christian spiritual ministries and church family occasions.',
    memberId: 'usr_paul',
    remindersSent: [],
  },
];

export const INITIAL_GROUPS: GroupItem[] = [
  {
    id: 'grp_youth',
    name: 'Youth Fellowship',
    description: 'Dynamic community of young people passionately chasing Christ and impacting their colleges and workplaces.',
    category: 'Youth',
    isPrivate: false,
    memberCount: 142,
    isMember: true,
    leaderId: 'usr_benny',
    leaderName: 'Benny Nagashetty',
    imageUrl: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=400&q=80',
    meetingSchedule: 'Every Saturday 6:00 PM',
  },
  {
    id: 'grp_women',
    name: 'Women’s Ministry (Ester Fellowship)',
    description: 'Encouraging sisters and mothers in prayer, godly parenting, and charitable support for the vulnerable.',
    category: 'Women’s',
    isPrivate: false,
    memberCount: 185,
    isMember: true,
    leaderId: 'usr_dorka',
    leaderName: 'Sister Dorka Rani',
    imageUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
    meetingSchedule: 'Every 1st & 3rd Friday 4:00 PM',
  },
  {
    id: 'grp_men',
    name: 'Men of Faith Fellowship',
    description: 'Building strong spiritual heads of households through accountability, scripture, and evangelism.',
    category: 'Men’s',
    isPrivate: false,
    memberCount: 96,
    isMember: false,
    leaderId: 'usr_john',
    leaderName: 'Deacon John Wesley',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    meetingSchedule: 'Every 2nd Saturday 7:30 AM',
  },
  {
    id: 'grp_worship',
    name: 'AAJM Worship Choir & Media',
    description: 'Ministers of music, singers, instrumentalists, sound engineers, and livestream camera crew.',
    category: 'Worship Team',
    isPrivate: true,
    memberCount: 38,
    isMember: true,
    leaderId: 'usr_blessy',
    leaderName: 'Sister Blessy',
    imageUrl: 'https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?auto=format&fit=crop&w=400&q=80',
    meetingSchedule: 'Thursday & Saturday 6:30 PM',
  },
  {
    id: 'grp_prayer',
    name: '24/7 Intercessory Prayer Warriors',
    description: 'Round-the-clock chain prayer standing in the gap for the sick, the church, and nation revival.',
    category: 'Prayer Group',
    isPrivate: false,
    memberCount: 84,
    isMember: true,
    leaderId: 'usr_pastor',
    leaderName: 'Pastor Daniel Nagashetty',
    imageUrl: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=400&q=80',
    meetingSchedule: 'Daily Continuous Slots',
  },
];

export const INITIAL_GROUP_MESSAGES: Record<string, GroupMessage[]> = {
  grp_youth: [
    {
      id: 'msg_1',
      groupId: 'grp_youth',
      senderId: 'usr_benny',
      senderName: 'Benny Nagashetty',
      senderRole: 'Group Leader',
      senderAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=128&q=80',
      text: 'Praise the Lord everyone! Reminder that our acoustic worship prep begins at 5:30 PM tomorrow before the main fellowship!',
      timestamp: '2026-09-19T06:45:00Z',
      type: 'text',
      reactions: [{ emoji: '🙏', count: 8, users: ['usr_admin_1', 'usr_john'] }, { emoji: '🔥', count: 5, users: ['usr_blessy'] }],
      readBy: ['usr_admin_1', 'usr_blessy'],
    },
    {
      id: 'msg_2',
      groupId: 'grp_youth',
      senderId: 'usr_blessy',
      senderName: 'Sister Blessy',
      senderRole: 'Choir Leader',
      text: 'Amen! The new Telugu praise song chords have also been updated in the files tab for everyone playing guitar and keys.',
      timestamp: '2026-09-19T07:15:00Z',
      type: 'text',
      reactions: [{ emoji: '❤️', count: 6, users: ['usr_benny'] }],
      readBy: ['usr_admin_1'],
    },
    {
      id: 'msg_3',
      groupId: 'grp_youth',
      senderId: 'usr_admin_1',
      senderName: 'Pastor Daniel Nagashetty',
      senderRole: 'Pastor',
      text: 'God bless you dear youth! Remember 1 Timothy 4:12 — Let no one despise your youth, but be an example to the believers in word, in conduct, in love, in spirit, in faith, in purity.',
      timestamp: '2026-09-19T08:00:00Z',
      type: 'text',
      reactions: [{ emoji: '🙌', count: 18, users: ['usr_benny', 'usr_blessy'] }, { emoji: '❤️', count: 14, users: [] }],
      readBy: ['usr_benny', 'usr_blessy'],
    },
  ],
};

export const INITIAL_PAYMENT_SETTINGS: PaymentSettings = {
  qrScannerImage: '', // Admin can upload real QR code scanner image
  upiId: 'aajmchurch@sbi',
  phonePe: '+91 98490 12345',
  googlePay: '+91 98490 12345',
  paytm: '+91 98490 12345',
  bankName: 'State Bank of India',
  accountName: 'ALL ARE JOYFUL MINISTRIES (AAJM CHURCH)',
  accountNumber: '38472910543',
  ifsc: 'SBIN0020144',
  branch: 'Secunderabad Main Branch, Hyderabad',
  instructions:
    'Please mention your Name and Purpose (e.g. Offering, Poor & Needy, Church Building) in the payment remarks/notes. Send transaction screenshot to WhatsApp: +91 98490 12345 for official 80G tax receipt.',
};

export const INITIAL_PRAYER_REQUESTS: PrayerRequest[] = [
  {
    id: 'pr_1',
    name: 'Brother Anand & Family',
    request: 'Please pray for my father’s recovery from heart bypass surgery and for peace and divine strength in our family.',
    category: 'Healing & Health',
    isPrivate: false,
    date: '2026-09-18',
    status: 'approved',
    prayedCount: 34,
    submittedBy: 'usr_anand',
    hasPrayed: false,
  },
  {
    id: 'pr_2',
    name: 'Sister Rachel',
    request: 'Seeking prayers for divine guidance in job interview this Tuesday and grace to be a witness for Christ.',
    category: 'Job & Career',
    isPrivate: false,
    date: '2026-09-19',
    status: 'prayed_for',
    prayedCount: 19,
    submittedBy: 'usr_rachel',
    hasPrayed: true,
  },
  {
    id: 'pr_3',
    name: 'Anonymous Sister',
    request: 'Private confidential family reconciliation prayer request.',
    category: 'Family Peace',
    isPrivate: true,
    date: '2026-09-17',
    status: 'approved',
    prayedCount: 12,
    submittedBy: 'usr_anon',
  },
];

export const INITIAL_CHILD_PROFILES: ChildProfile[] = [
  {
    id: 'child_1',
    parentId: 'usr_admin_1',
    name: 'Joshua',
    age: 9,
    avatar: '👦',
    bibleStars: 280,
    streakDays: 7,
    currentAdventureStage: 'David',
    badges: ['First Bible Quiz', 'Bible Explorer', 'Memory Verse Beginner', '7-Day Streak', 'Sunday School Star'],
  },
  {
    id: 'child_2',
    parentId: 'usr_admin_1',
    name: 'Esther',
    age: 6,
    avatar: '👧',
    bibleStars: 190,
    streakDays: 4,
    currentAdventureStage: 'Noah',
    badges: ['First Bible Quiz', 'Memory Verse Beginner', 'Sunday School Star'],
  },
];

export const INITIAL_QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 'quiz_1',
    category: 'Old Testament',
    language: 'en',
    difficulty: 'easy',
    question: 'How many days and nights did it rain when Noah was inside the ark?',
    options: ['7 days and 7 nights', '40 days and 40 nights', '120 days', '3 days and 3 nights'],
    correctAnswerIndex: 1,
    explanation: 'Genesis 7:12 tells us that rain fell upon the earth for forty days and forty nights.',
  },
  {
    id: 'quiz_1_te',
    category: 'Old Testament',
    language: 'te',
    difficulty: 'easy',
    question: 'నోవహు ఓడలో ఉన్నప్పుడు ఎన్ని పగళ్ళు మరియు రాత్రులు వర్షం కురిసింది?',
    options: ['7 పగళ్ళు మరియు 7 రాత్రులు', '40 పగళ్ళు మరియు 40 రాత్రులు', '120 రోజులు', '3 పగళ్ళు మరియు 3 రాత్రులు'],
    correctAnswerIndex: 1,
    explanation: 'ఆదికాండము 7:12 ప్రకారం నలువది పగళ్ళును నలువది రాత్రులును భూమిమీద వర్షము కురిసెను.',
  },
  {
    id: 'quiz_2',
    category: 'Jesus',
    language: 'en',
    difficulty: 'easy',
    question: 'In which town was Jesus Christ born?',
    options: ['Nazareth', 'Jerusalem', 'Bethlehem', 'Capernaum'],
    correctAnswerIndex: 2,
    explanation: 'Jesus was born in Bethlehem of Judea in the days of King Herod (Matthew 2:1).',
  },
  {
    id: 'quiz_2_te',
    category: 'Jesus',
    language: 'te',
    difficulty: 'easy',
    question: 'యేసుక్రీస్తు ఏ ఊరిలో జన్మించారు?',
    options: ['నజరేతు', 'యెరూషలేము', 'బెత్లెహేము', 'కపెర్నహూము'],
    correctAnswerIndex: 2,
    explanation: 'మత్తయి 2:1 ప్రకారం యూదయ దేశపు బెత్లెహేములో యేసు జన్మించెను.',
  },
  {
    id: 'quiz_3',
    category: 'Bible Characters',
    language: 'en',
    difficulty: 'medium',
    question: 'Which weapon did young David use to defeat the giant Goliath?',
    options: ['Iron sword and shield', 'Sling and five smooth stones', 'Spear of bronze', 'Bow and arrow'],
    correctAnswerIndex: 1,
    explanation: 'David took his staff, chose five smooth stones from the brook, and with his sling struck Goliath (1 Samuel 17:40).',
  },
  {
    id: 'quiz_3_te',
    category: 'Bible Characters',
    language: 'te',
    difficulty: 'medium',
    question: 'దావీదు గొల్యాతును ఓడించడానికి ఏ ఆయుధాన్ని ఉపయోగించాడు?',
    options: ['ఇనుప కత్తి మరియు డాలు', 'ఒడిసెల మరియు ఏటిలో ఏరుకున్న 5 నునుపైన రాళ్ళు', 'కంచు బల్లెం', 'విల్లు మరియు బాణాలు'],
    correctAnswerIndex: 1,
    explanation: '1 సమూయేలు 17:40 ప్రకారం దావీదు ఐదు నునుపైన రాళ్ళను ఏరుకొని తన ఒడిసెలతో గొల్యాతును జయించెను.',
  },
  {
    id: 'quiz_4',
    category: 'Bible Verses',
    language: 'en',
    difficulty: 'easy',
    question: 'Complete the verse: "The Lord is my shepherd; I shall not ______" (Psalm 23:1)',
    options: ['fear', 'want', 'stumble', 'sleep'],
    correctAnswerIndex: 1,
    explanation: 'Psalm 23:1 says, "The Lord is my shepherd; I shall not want."',
  },
  {
    id: 'quiz_4_te',
    category: 'Bible Verses',
    language: 'te',
    difficulty: 'easy',
    question: 'వాక్యాన్ని పూర్తి చేయండి: "యెహోవా నా కాపరి; నాకు ______ కలగదు" (కీర్తన 23:1)',
    options: ['భయం', 'లేమి', 'దుఃఖం', 'అలసట'],
    correctAnswerIndex: 1,
    explanation: 'కీర్తన 23:1 ప్రకారం "యెహోవా నా కాపరి నాకు లేమి కలుగదు."',
  },
  {
    id: 'quiz_5',
    category: 'Apostles',
    language: 'en',
    difficulty: 'medium',
    question: 'Who was swallowed by a great fish when running away from God to Tarshish?',
    options: ['Elijah', 'Jonah', 'Paul', 'Daniel'],
    correctAnswerIndex: 1,
    explanation: 'Jonah boarded a ship to Tarshish and was swallowed by a great fish for 3 days (Jonah 1:17).',
  },
  {
    id: 'quiz_5_te',
    category: 'Apostles',
    language: 'te',
    difficulty: 'medium',
    question: 'దేవుని మాటకు అవిధేయుడై తర్షీషుకు పారిపోతుండగా పెద్ద చేప చేత మింగబడిన ప్రవక్త ఎవరు?',
    options: ['ఏలీయా', 'యోనా', 'పౌలు', 'దానియేలు'],
    correctAnswerIndex: 1,
    explanation: 'యోనా 1:17 ప్రకారం యెహోవా యోనాను మింగుటకు ఒక గొప్ప మత్స్యమును నియమించెను.',
  },
];

export const INITIAL_BIBLE_STORIES: BibleStory[] = [
  {
    id: 'story_noah',
    title: 'Noah’s Ark & God’s Rainbow Promise',
    character: 'Noah',
    summary: 'God told faithful Noah to build a giant wooden ark to save his family and pairs of every living animal from the great flood.',
    paragraphs: [
      'In a time when people had forgotten God’s kindness, Noah walked faithfully with God.',
      'God commanded Noah to build an enormous ark out of gopher wood and seal it with pitch inside and out.',
      'Noah obeyed every instruction. Pairs of birds, cattle, and creeping animals came peacefully into the ark.',
      'When the rain poured for forty days, God shut the door of the ark safely. At last, the waters receded and God put a glorious rainbow in the sky as an everlasting promise of His faithful love!'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    scriptureReference: 'Genesis 6 - 9',
    memoryVerse: '“I have set my rainbow in the clouds, and it will be the sign of the covenant between me and the earth.” — Genesis 9:13',
    audioNarrationText: 'Listen to the wonderful story of Noah who trusted God when everyone else laughed. God always honors faithful obedience!',
  },
  {
    id: 'story_david',
    title: 'David and Goliath: Faith Over Fear',
    character: 'David',
    summary: 'A young shepherd boy armed only with faith in the Living God and five smooth stones defeats the terrifying giant Goliath.',
    paragraphs: [
      'David cared for his father’s sheep and sang praises to God on his harp in the hills of Bethlehem.',
      'When the mighty Philistine champion Goliath dared the armies of Israel, all the soldiers trembled in fear.',
      'David arrived and boldly declared: “You come against me with sword and spear and javelin, but I come against you in the name of the Lord Almighty!”',
      'With one smooth stone slung in faith, the stone struck Goliath’s forehead and the giant fell! God showed the entire world that victory belongs to the Lord.'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=600&q=80',
    scriptureReference: '1 Samuel 17',
    memoryVerse: '“The battle is the Lord’s, and he will give all of you into our hands.” — 1 Samuel 17:47',
    audioNarrationText: 'David knew that God was bigger than any giant in this world. When you face fear, remember Jesus is with you!',
  },
  {
    id: 'story_daniel',
    title: 'Daniel in the Lions’ Den',
    character: 'Daniel',
    summary: 'Daniel refused to stop praying to God three times a day, and God sent His angel to shut the lions’ hungry mouths.',
    paragraphs: [
      'Daniel was an honest, excellent leader in Babylon who loved the Lord with all his heart.',
      'Even when jealous men made a law banning prayer to anyone except the king, Daniel opened his window toward Jerusalem and knelt in prayer three times daily.',
      'He was thrown into a den of hungry roaring lions! But God sent His angel to shut the lions’ mouths so that not a single scratch was found upon him.',
      'King Darius rejoiced and proclaimed across the whole empire that Daniel’s God is the Living God who rescues and delivers forever!'
    ],
    imageUrl: 'https://images.unsplash.com/photo-1534188753412-3e26d0d618d6?auto=format&fit=crop&w=600&q=80',
    scriptureReference: 'Daniel 6',
    memoryVerse: '“My God sent his angel, and he shut the mouths of the lions.” — Daniel 6:22',
    audioNarrationText: 'Never be afraid to pray to Jesus anywhere! God’s angels watch over everyone who loves Him.',
  },
];

export const INITIAL_MEMORY_VERSES: MemoryVerseAssignment[] = [
  {
    id: 'mv_week_1',
    weekNumber: 1,
    verse: '“I can do all things through Christ who strengthens me.”',
    scriptureReference: 'Philippians 4:13',
    language: 'en',
    description: 'Learn this powerful verse by heart. Record your voice or video reciting it clearly!',
    deadline: 'Saturday, 11:59 PM',
    ageGroup: 'All Sunday School Children',
    className: 'Joyful Juniors & Kingdom Kids',
  },
  {
    id: 'mv_week_1_te',
    weekNumber: 1,
    verse: '“నన్ను బలపరచువానియందే నేను సమస్తమును చేయగలను.”',
    scriptureReference: 'ఫిలిప్పీయులకు 4:13',
    language: 'te',
    description: 'ఈ వాక్యాన్ని శ్రద్ధగా కంఠస్థం చేసి మీ గళంతో లేదా వీడియోతో రికార్డ్ చేసి టీచర్‌కు పంపించండి!',
    deadline: 'శనివారం రాత్రి 11:59 వరకు',
    ageGroup: 'అన్ని సండే స్కూల్ తరగతులు',
    className: 'ఆనంద తరగతి',
  },
];

export const INITIAL_SUNDAY_SCHOOL_CLASSES: SundaySchoolClass[] = [
  {
    id: 'cls_1',
    name: 'Little Lambs (Ages 3-5)',
    ageGroup: '3 to 5 years',
    teacherId: 'usr_sarah',
    teacherName: 'Teacher Sarah',
    weeklyLesson: 'Jesus Loves the Little Children',
    memoryVerse: 'God is love (1 John 4:8)',
    studentCount: 22,
    schedule: 'Sunday 10:00 AM - Room 101',
  },
  {
    id: 'cls_2',
    name: 'Kingdom Kids (Ages 6-9)',
    ageGroup: '6 to 9 years',
    teacherId: 'usr_rachel_t',
    teacherName: 'Teacher Rachel',
    weeklyLesson: 'David and Goliath: Trusting God in Trials',
    memoryVerse: 'The Lord is my shepherd (Psalm 23:1)',
    studentCount: 34,
    schedule: 'Sunday 10:00 AM - Room 102',
  },
  {
    id: 'cls_3',
    name: 'Champions for Christ (Ages 10-14)',
    ageGroup: '10 to 14 years',
    teacherId: 'usr_benny',
    teacherName: 'Teacher Benny Nagashetty',
    weeklyLesson: 'Armor of God & Overcoming Peer Pressure',
    memoryVerse: 'I can do all things through Christ (Philippians 4:13)',
    studentCount: 28,
    schedule: 'Sunday 10:00 AM - Youth Hall',
  },
];

export const BADGES_LIST: BadgeItem[] = [
  { id: 'b_1', name: 'First Bible Quiz', description: 'Completed first interactive Bible quiz', icon: '⭐', requiredStars: 20 },
  { id: 'b_2', name: 'Bible Explorer', description: 'Completed 3 Bible story journeys', icon: '🗺️', requiredStars: 60 },
  { id: 'b_3', name: 'Memory Verse Beginner', description: 'Memorized and submitted 1 weekly verse', icon: '📜', requiredStars: 100 },
  { id: 'b_4', name: 'Memory Verse Champion', description: 'Approved for 5 consecutive memory verses', icon: '🏆', requiredStars: 250 },
  { id: 'b_5', name: '7-Day Streak', description: 'Studied Bible story or played quiz 7 days in a row', icon: '🔥', requiredStars: 150 },
  { id: 'b_6', name: '30-Day Streak', description: 'Faithful disciple active for 30 consecutive days', icon: '💎', requiredStars: 500 },
  { id: 'b_7', name: 'Sunday School Star', description: 'Perfect attendance in Sunday School this month', icon: '🌟', requiredStars: 180 },
  { id: 'b_8', name: 'Bible Knowledge Star', description: 'Scored 100% in Hard Old Testament Quiz', icon: '👑', requiredStars: 300 },
  { id: 'b_9', name: 'Quiz Champion', description: 'Answered over 50 quiz questions correctly', icon: '🎯', requiredStars: 350 },
  { id: 'b_10', name: 'Prayer Warrior', description: 'Shared prayers for church and family missions', icon: '🕊️', requiredStars: 200 },
  { id: 'b_11', name: 'Bible Adventure Completed', description: 'Finished Genesis through Apostles adventure track', icon: '🚀', requiredStars: 700 },
];

export const INITIAL_LEADERBOARD: LeaderboardChild[] = [
  { rank: 1, name: 'Joshua D.', avatar: '👦', stars: 280, versesMemorized: 6, badgesCount: 5, isCurrentChild: true },
  { rank: 2, name: 'Aaron K.', avatar: '🧒', stars: 250, versesMemorized: 5, badgesCount: 4 },
  { rank: 3, name: 'Miriam P.', avatar: '👧', stars: 230, versesMemorized: 5, badgesCount: 4 },
  { rank: 4, name: 'Esther D.', avatar: '👧', stars: 190, versesMemorized: 4, badgesCount: 3, isCurrentChild: true },
  { rank: 5, name: 'Samuel R.', avatar: '👦', stars: 175, versesMemorized: 3, badgesCount: 3 },
  { rank: 6, name: 'Ruth V.', avatar: '👧', stars: 140, versesMemorized: 2, badgesCount: 2 },
];
