export type AppLanguage = 'en' | 'te';

export const TRANSLATIONS = {
  en: {
    appTitle: 'AAJM CHURCH',
    tagline: 'All Are Joyful Ministries',
    events: 'Events',
    home: 'Home',
    booking: 'Booking',
    groups: 'Groups',
    location: 'Location',
    notifications: 'Notifications',
    profile: 'Profile',
    calls: 'Calls',
    pastorScheduleTitle: 'PASTOR DANIEL NAGASHETTY',
    weeklyScheduleSubtitle: 'Weekly Schedule',
    noticeBoard: 'NOTICE BOARD',
    moreFeatures: 'MORE FEATURES',
    churchLocation: 'CHURCH LOCATION',
    photosAndMedia: 'Photos & Media',
    prayerRequest: 'Prayer Request',
    liveServices: 'Live Services',
    offeringsAndDonations: 'Offerings & Donations',
    supportPoorAndNeedy: 'Support Poor & Needy People',
    bankDetails: 'Bank Details',
    contactUs: 'Contact Us',
    founderAndFamily: 'Founder & Family',
    documents: 'Documents',
    attendance: 'Attendance',
    childrenMode: 'Children Mode',
    adminDashboard: 'Admin Dashboard',
    hostDashboard: 'Host Dashboard',
    groupLeaderDashboard: 'Group Leader Dashboard',
    teacherDashboard: 'Teacher Dashboard',
    available: 'Available',
    pending: 'Pending',
    confirmed: 'Confirmed',
    rejected: 'Rejected',
    bookSlot: 'Book Appointment / Slot',
    rsvpNow: 'RSVP Now',
    cancelRsvp: 'Cancel RSVP',
    joinGroup: 'Join Group',
    sendMessage: 'Send Message...',
    submitPrayer: 'Submit Prayer Request',
    viewAllNotices: 'View All Notices',
    search: 'Search...',
    allCategories: 'All Categories',
    emergency: 'Emergency',
    important: 'Important',
    prayer: 'Prayer',
    general: 'General',
    enterChildrenMode: 'Switch to Children Mode',
    exitChildrenMode: 'Exit Children Mode',
    bibleStars: 'Bible Stars',
    leaderboard: 'Leaderboard',
    memoryVerse: 'Memory Verse',
    sundaySchool: 'Sunday School',
    bibleQuiz: 'Bible Quiz',
    bibleGames: 'Bible Games',
    bibleStories: 'Bible Stories',
    recordVerse: 'Record Memory Verse',
    startRecording: 'Start Recording',
    stopRecording: 'Stop Recording',
    submitRecording: 'Submit to Teacher',
    uploadPhoto: 'Upload Photo',
    uploadQr: 'Upload QR Scanner',
    directions: 'Get Directions',
    upcomingEvents: 'Upcoming Events',
    pastEvents: 'Past Events',
  },
  te: {
    appTitle: 'ఏఏజేఎమ్ చర్చి',
    tagline: 'ఆల్ ఆర్ జాయ్‌ఫుల్ మినిస్ట్రీస్',
    events: 'కార్యక్రమాలు',
    home: 'హోమ్',
    booking: 'బుకింగ్',
    groups: 'సమూహాలు',
    location: 'స్థల వివరాలు',
    notifications: 'నోటిఫికేషన్లు',
    profile: 'ప్రొఫైల్',
    calls: 'కాల్స్',
    pastorScheduleTitle: 'పాస్టర్ డేనియల్ నాగశెట్టి',
    weeklyScheduleSubtitle: 'వారపు షెడ్యూల్',
    noticeBoard: 'నోటీస్ బోర్డు',
    moreFeatures: 'మరిన్ని సేవలు',
    churchLocation: 'చర్చి లొకేషన్',
    photosAndMedia: 'ఫోటోలు & మీడియా',
    prayerRequest: 'ప్రార్థన విన్నపం',
    liveServices: 'ప్రత్యక్ష ఆరాధన (Live)',
    offeringsAndDonations: 'కానుకలు & దానాలు',
    supportPoorAndNeedy: 'పేదలకు & అవసరంలో ఉన్నవారికి సహాయం',
    bankDetails: 'బ్యాంకు వివరాలు',
    contactUs: 'సంప్రదించండి',
    founderAndFamily: 'వ్యవస్థాపకుడు & కుటుంబం',
    documents: 'పత్రాలు & నోట్స్',
    attendance: 'హాజరు',
    childrenMode: 'పిల్లల మోడ్',
    adminDashboard: 'అడ్మిన్ డాష్‌బోర్డ్',
    hostDashboard: 'హోస్ట్ డాష్‌బోర్డ్',
    groupLeaderDashboard: 'గ్రూప్ లీడర్ డాష్‌బోర్డ్',
    teacherDashboard: 'సండే స్కూల్ టీచర్ డాష్‌బోర్డ్',
    available: 'అందుబాటులో ఉంది',
    pending: 'పరిశీలనలో ఉంది',
    confirmed: 'ఖరారైంది',
    rejected: 'తిరస్కరించబడింది',
    bookSlot: 'స్లాట్ బుక్ చేయండి',
    rsvpNow: 'రిజిస్టర్ అవ్వండి',
    cancelRsvp: 'రద్దు చేసుకోండి',
    joinGroup: 'గ్రూప్‌లో చేరండి',
    sendMessage: 'సందేశం పంపండి...',
    submitPrayer: 'ప్రార్థన అభ్యర్థన పంపండి',
    viewAllNotices: 'అన్ని నోటీసులు చూడండి',
    search: 'వెతకండి...',
    allCategories: 'అన్ని విభాగాలు',
    emergency: 'అత్యవసరం',
    important: 'ముఖ్యమైనది',
    prayer: 'ప్రార్థన',
    general: 'సాధారణ',
    enterChildrenMode: 'పిల్లల మోడ్‌లోకి మారండి',
    exitChildrenMode: 'పిల్లల మోడ్ నుండి నిష్క్రమించండి',
    bibleStars: 'బైబిల్ స్టార్స్',
    leaderboard: 'లీడర్‌బోర్డ్',
    memoryVerse: 'కంఠస్థ వాక్యము',
    sundaySchool: 'సండే స్కూల్',
    bibleQuiz: 'బైబిల్ క్విజ్',
    bibleGames: 'బైబిల్ ఆటలు',
    bibleStories: 'బైబిల్ కథలు',
    recordVerse: 'కంఠస్థ వాక్యము రికార్డ్ చేయండి',
    startRecording: 'రికార్డింగ్ ప్రారంభించండి',
    stopRecording: 'రికార్డింగ్ ఆపండి',
    submitRecording: 'టీచర్‌కు పంపండి',
    uploadPhoto: 'ఫోటో అప్‌లోడ్ చేయండి',
    uploadQr: 'క్యూఆర్ కోడ్ అప్‌లోడ్ చేయండి',
    directions: 'దారి మార్గం',
    upcomingEvents: 'రాబోయే కార్యక్రమాలు',
    pastEvents: 'గత కార్యక్రమాలు',
  },
};
